"""ViDrive PDF Export via LaTeX - generates professional TCO reports."""
import subprocess
import shutil
from datetime import date
from pathlib import Path
from src.i18n import t, _lang
from src.config import PARKING_TOLL_ESTIMATES


def _generate_text_report_single(car_id: str, year: int, res: dict, city: str, km: int, years: int, area: int, ratio: float, show_opp: bool, loan: dict = None) -> str:
    """Generate plain-text report for single car."""
    lines = []
    lines.append("=" * 60)
    lines.append("ViDrive TCO Report")
    lines.append("=" * 60)
    lines.append(f"Vehicle: {car_id.upper()}")
    lines.append(f"Date: {date.today().strftime('%d/%m/%Y')}")
    lines.append(f"City: {city.title()} | Area: {area} | Annual KM: {km:,} | Years: {years}")
    lines.append(f"City Ratio: {ratio*100:.0f}% city / {100-ratio*100:.0f}% highway")
    lines.append(f"Language: {'English' if _lang == 'en' else 'Tiếng Việt'} | ViDrive v0.5.0")
    lines.append("")
    
    lines.append("-" * 60)
    lines.append("SUMMARY")
    lines.append("-" * 60)
    lines.append(f"  On-road Price:     {res['on_road']:>15,.0f} VND")
    lines.append(f"  Net TCO ({years} yr): {res['tco']:>15,.0f} VND")
    if show_opp:
        lines.append(f"  Opportunity Cost:  {res['opp_cost']:>15,.0f} VND")
        lines.append(f"  True Impact:       {res['true_financial_impact']:>15,.0f} VND")
    lines.append(f"  Monthly Average:   {res['monthly']:>15,.0f} VND")
    lines.append("")
    
    lines.append("-" * 60)
    lines.append("1. INITIAL OUTLAY")
    lines.append("-" * 60)
    lines.append(f"  MSRP Price:        {res['price']:>15,.0f} VND")
    lines.append(f"  Registration Tax:  {res['reg_tax']:>15,.0f} VND")
    lines.append(f"  Total Outlay:      {res['on_road']:>15,.0f} VND")
    lines.append("")
    
    lines.append("-" * 60)
    lines.append("2. OPERATING COSTS")
    lines.append("-" * 60)
    lines.append(f"  Fuel / Energy:     {res['fuel']:>15,.0f} VND")
    lines.append(f"  Maintenance:       {res['maint']:>15,.0f} VND")
    lines.append(f"  Insurance & Fees:  {res['legal']:>15,.0f} VND")
    lines.append(f"  Total Operating:   {res['operating']:>15,.0f} VND")
    pt = res.get('parking_toll')
    if pt:
        lines.append(f"  Parking & Tolls:   {pt['total_over_period']:>15,.0f} VND (provision)")
        lines.append(f"    Monthly Parking: {pt['monthly_parking']:>15,.0f} VND")
        lines.append(f"    Monthly Toll:    {pt['monthly_toll']:>15,.0f} VND")
    lines.append("")
    lines.append("(Note: Parking & Toll estimates are provisions, not included in TCO total.)")
    lines.append("")
    
    lines.append("-" * 60)
    lines.append("3. RESALE & DEPRECIATION")
    lines.append("-" * 60)
    lines.append(f"  Predicted Resale:  {res['resale']:>15,.0f} VND")
    lines.append(f"  Total Depreciation:{res['depreciation']:>15,.0f} VND")
    raw_liq = res.get('liquidity', '')
    if raw_liq.startswith('Tier 1'):
        liq_disp = t('tier_1')
    elif raw_liq.startswith('Tier 2'):
        liq_disp = t('tier_2')
    else:
        liq_disp = t('tier_3')
    lines.append(f"  Resale Method:     {t('resale_logic_' + res['resale_logic'])}")
    lines.append(f"  Liquidity:         {liq_disp}")
    lines.append("")
    
    if loan:
        lines.append("-" * 60)
        lines.append("4. LOAN / FINANCING PLAN")
        lines.append("-" * 60)
        lines.append(f"  Monthly Payment:    {loan['monthly_payment']:>15,.0f} VND")
        lines.append(f"  Total Interest:     {loan['total_interest']:>15,.0f} VND")
        lines.append(f"  Total Repayment:    {loan['total_repayment']:>15,.0f} VND")
        lines.append(f"  Effective Cost:     {loan['effective_cost']:>15,.0f} VND")
        lines.append("")
    
    lines.append("-" * 60)
    lines.append("ASSUMPTIONS")
    lines.append("-" * 60)
    area_names = {1: "Area 1 (Central City)", 2: "Area 2 (Provincial City)", 3: "Area 3 (Rural/District)"}
    area_name = area_names.get(area, "Area 2")
    lines.append(f"  City/Province:     {city.title()}")
    lines.append(f"  Area:              {area_name}")
    lines.append(f"  Annual KM:         {km:,}")
    lines.append(f"  Years:             {years}")
    lines.append(f"  City/Highway Split:{ratio*100:.0f}% / {100-ratio*100:.0f}%")
    lines.append(f"  Opportunity Cost:  {'Yes' if show_opp else 'No'}")
    lines.append("")
    lines.append("-" * 60)
    lines.append("Generated by ViDrive TCO Calculator v0.5.0")
    lines.append("For informational purposes only. Not financial advice.")
    lines.append("=" * 60)
    
    return "\n".join(lines)


def _generate_text_report_compare(cars_data: list, results: list, year: int, city: str, km: int, years: int, area: int, ratio: float, show_opp: bool, loans: list = None) -> str:
    """Generate plain-text report for multi-car comparison."""
    car_ids = [c.upper() for c in cars_data]
    n = len(car_ids)
    
    lines = []
    lines.append("=" * 80)
    lines.append("ViDrive TCO Comparison Report")
    lines.append("=" * 80)
    lines.append(f"Vehicles: {' vs '.join(car_ids)}")
    lines.append(f"Date: {date.today().strftime('%d/%m/%Y')}")
    lines.append(f"City: {city.title()} | Area: {area} | Annual KM: {km:,} | Years: {years}")
    lines.append(f"City Ratio: {ratio*100:.0f}% city / {100-ratio*100:.0f}% highway")
    lines.append(f"Language: {'English' if _lang == 'en' else 'Tiếng Việt'} | ViDrive v0.5.0")
    lines.append("")
    
    # Summary table
    lines.append("-" * 80)
    lines.append("COMPARISON SUMMARY")
    lines.append("-" * 80)
    
    header = f"{'Metric':<30}"
    for cid in car_ids:
        header += f"{cid:>22}"
    lines.append(header)
    lines.append("-" * 80)
    
    def add_row(label, vals):
        row = f"{label:<30}"
        for v in vals:
            row += f"{v:>22}"
        lines.append(row)
    
    add_row("On-road Price", [_fmt_vnd(r['on_road']) for r in results])
    add_row(f"Net TCO ({years} yr)", [_fmt_vnd(r['tco']) for r in results])
    if show_opp:
        add_row("Opportunity Cost", [_fmt_vnd(r['opp_cost']) for r in results])
        add_row("True Impact", [_fmt_vnd(r['true_financial_impact']) for r in results])
    add_row("Monthly Average", [_fmt_vnd(r['monthly']) for r in results])
    lines.append("")
    
    # Initial Outlay
    lines.append("-" * 80)
    lines.append("1. INITIAL OUTLAY")
    lines.append("-" * 80)
    for k, label in [('price', 'MSRP Price'), ('reg_tax', 'Registration Tax'), ('on_road', 'Total Outlay')]:
        add_row(label, [_fmt_vnd(r[k]) for r in results])
    lines.append("")
    
    # Operating Costs
    lines.append("-" * 80)
    lines.append("2. OPERATING COSTS")
    lines.append("-" * 80)
    for k, label in [('fuel', 'Fuel / Energy'), ('maint', 'Maintenance'), ('operating', 'Total Operating')]:
        add_row(label, [_fmt_vnd(r[k]) for r in results])
    lines.append("")
    
    # Parking & Toll
    lines.append("-" * 80)
    lines.append("PARKING & TOLLS (Provisions)")
    lines.append("-" * 80)
    for i, r in enumerate(results):
        pt = r.get('parking_toll')
        if pt:
            lines.append(f"  {car_ids[i]}:")
            lines.append(f"    Monthly Parking: {_fmt_vnd(pt['monthly_parking'])}")
            lines.append(f"    Monthly Toll:    {_fmt_vnd(pt['monthly_toll'])}")
            lines.append(f"    Total ({years} yr):  {_fmt_vnd(pt['total_over_period'])}")
    lines.append("(Note: Parking & Toll estimates are provisions, not included in TCO total.)")
    lines.append("")
    
    # Resale & Depreciation
    lines.append("-" * 80)
    lines.append("3. RESALE & DEPRECIATION")
    lines.append("-" * 80)
    for k, label in [('resale', 'Predicted Resale'), ('depreciation', 'Total Depreciation')]:
        add_row(label, [_fmt_vnd(r[k]) for r in results])
    lines.append(f"  Resale Method:     {t('resale_logic_' + results[0]['resale_logic'])}")
    
    # Brand Liquidity
    lines.append("  Brand Liquidity:")
    for i, r in enumerate(results):
        raw_liq = r.get('liquidity', '')
        if raw_liq.startswith('Tier 1'):
            liq_disp = t('tier_1')
        elif raw_liq.startswith('Tier 2'):
            liq_disp = t('tier_2')
        else:
            liq_disp = t('tier_3')
        lines.append(f"    {car_ids[i]}: {liq_disp}")
    lines.append("")
    
    # Loan
    if loans:
        lines.append("-" * 80)
        lines.append("4. LOAN / FINANCING PLAN")
        lines.append("-" * 80)
        for k, label in [
            ('monthly_payment', 'Monthly Payment'),
            ('total_interest', 'Total Interest'),
            ('total_repayment', 'Total Repayment'),
            ('effective_cost', 'Effective Cost'),
        ]:
            add_row(label, [_fmt_vnd(loan[k]) for loan in loans])
        lines.append("")
    
    # Verdict
    lines.append("-" * 80)
    lines.append("VERDICT")
    lines.append("-" * 80)
    min_idx = min(range(n), key=lambda i: results[i]['tco'])
    winner = car_ids[min_idx]
    for i in range(n):
        if i != min_idx:
            diff = results[i]['tco'] - results[min_idx]['tco']
            lines.append(f"  {winner} is MORE ECONOMICAL by {_fmt_vnd(abs(diff))} vs {car_ids[i]}")
    lines.append("")
    
    # Assumptions
    lines.append("-" * 80)
    lines.append("ASSUMPTIONS")
    lines.append("-" * 80)
    area_names = {1: "Area 1 (Central City)", 2: "Area 2 (Provincial City)", 3: "Area 3 (Rural/District)"}
    area_name = area_names.get(area, "Area 2")
    lines.append(f"  City/Province:     {city.title()}")
    lines.append(f"  Area:              {area_name}")
    lines.append(f"  Annual KM:         {km:,}")
    lines.append(f"  Years:             {years}")
    lines.append(f"  City/Highway Split:{ratio*100:.0f}% / {100-ratio*100:.0f}%")
    lines.append(f"  Opportunity Cost:  {'Yes' if show_opp else 'No'}")
    lines.append("")
    lines.append("-" * 80)
    lines.append("Generated by ViDrive TCO Calculator v0.5.0")
    lines.append("For informational purposes only. Not financial advice.")
    lines.append("=" * 80)
    
    return "\n".join(lines)



def _check_pdflatex() -> bool:
    """Check if pdflatex is available."""
    return shutil.which("pdflatex") is not None


def _escape_latex(text: str) -> str:
    """Escape special LaTeX characters."""
    # Order matters: backslash must be replaced FIRST to avoid double-escaping
    replacements = [
        ('\\', r'\textbackslash{}'),
        ('&', r'\&'),
        ('%', r'\%'),
        ('$', r'\$'),
        ('#', r'\#'),
        ('_', r'\_'),
        ('{', r'\{'),
        ('}', r'\}'),
        ('~', r'\textasciitilde{}'),
        ('^', r'\textasciicircum{}'),
    ]
    for char, esc in replacements:
        text = text.replace(char, esc)
    return text


def _fmt_vnd(amount) -> str:
    """Format as VND with commas."""
    return f"{amount:,.0f} VND"


def _generate_latex_header(title: str) -> str:
    """Generate LaTeX document header."""
    today = date.today().strftime("%d/%m/%Y")
    lang_name = "English" if _lang == 'en' else "Tiếng Việt"
    
    return f"""\\documentclass[11pt,a4paper]{{article}}
\\usepackage[utf8]{{inputenc}}
\\usepackage[T1]{{fontenc}}
\\usepackage{{geometry}}
\\usepackage{{booktabs}}
\\usepackage{{longtable}}
\\usepackage{{array}}
\\usepackage{{xcolor}}
\\usepackage{{graphicx}}
\\geometry{{margin=2cm}}
\\definecolor{{ViDriveBlue}}{{RGB}}{{0, 82, 204}}
\\definecolor{{ViDriveGray}}{{RGB}}{{240, 240, 240}}
\\definecolor{{WinnerGreen}}{{RGB}}{{0, 128, 0}}

\\begin{{document}}
\\thispagestyle{{empty}}

% Header
\\begin{{center}}
    {{\\LARGE \\textbf{{\\color{{ViDriveBlue}} ViDrive TCO Report}}}}\\\\[0.3cm]
    {{\\Large {_escape_latex(title)}}}\\\\[0.2cm]
    {{\\normalsize Generated: {today} | Language: {lang_name} | ViDrive v0.5.0}}
\\end{{center}}
\\vspace{{0.5cm}}
\\hrule
\\vspace{{0.5cm}}
"""


def _generate_latex_footer() -> str:
    """Generate LaTeX document footer."""
    return """
\\vspace{1cm}
\\hrule
\\vspace{0.3cm}
\\begin{center}
    {\\small Generated by ViDrive TCO Calculator v0.5.0}\\\\
    {\\small \\textit{For informational purposes only. Not financial advice.}}
\\end{center}
\\end{document}
"""


def _assumptions_box(city: str, km: int, years: int, area: int, city_ratio: float, show_opp: bool) -> str:
    """Generate assumptions box as a table."""
    area_names = {1: "Area 1 (Central City)", 2: "Area 2 (Provincial City)", 3: "Area 3 (Rural/District)"}
    area_name = area_names.get(area, "Area 2")
    
    lines = [
        r"\begin{center}",
        r"\begin{tabular}{l l}",
        r"\toprule",
        f"{t('prompt_city').replace(':', '')} & {_escape_latex(city.title())} \\\\",
        f"{t('prompt_area_result', city=city.title(), area=area).replace('→', '->')} & {_escape_latex(area_name)} \\\\",
        f"{t('prompt_annual_km').replace(':', '')} & {km:,} km \\\\",
        f"{t('prompt_years').replace(':', '')} & {years} years \\\\",
        f"{t('prompt_city_ratio').replace(':', '').replace('%', '')} & {city_ratio*100:.0f}\\% city / {100-city_ratio*100:.0f}\\% highway \\\\",
        f"{t('prompt_opp_cost').replace(':', '').replace('?', '')} & {'Yes' if show_opp else 'No'} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{center}",
        r"\vspace{0.5cm}",
    ]
    return "\n".join(lines)


def _section_table(rows: list, col_count: int = 2) -> str:
    """Generate a LaTeX table for a section."""
    if col_count == 2:
        col_spec = "l r"
    else:
        col_spec = "l" + " r" * col_count
    
    lines = [f"\\begin{{tabular}}{{{col_spec}}}", r"\toprule"]
    for row in rows:
        if len(row) == 2:
            lines.append(f"{_escape_latex(row[0])} & {_escape_latex(row[1])} \\\\")
        elif len(row) == 3:
            lines.append(f"{_escape_latex(row[0])} & {_escape_latex(row[1])} & {_escape_latex(row[2])} \\\\")
        elif len(row) == 4:
            lines.append(f"{_escape_latex(row[0])} & {_escape_latex(row[1])} & {_escape_latex(row[2])} & {_escape_latex(row[3])} \\\\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\vspace{0.3cm}"])
    return "\n".join(lines)


def generate_pdf_single(car_id: str, year: int, res: dict, city: str, km: int, years: int, area: int, ratio: float, show_opp: bool, loan: dict = None) -> str:
    """Generate PDF for single car TCO analysis."""
    pdflatex_available = _check_pdflatex()
    
    filename_base = f"vidrive_{car_id.lower()}_{date.today().strftime('%Y%m%d')}"
    tex_file = Path.cwd() / f"{filename_base}.tex"
    pdf_file = Path.cwd() / f"{filename_base}.pdf"
    
    # Build LaTeX content
    title = f"{car_id.upper()} | {t('prompt_annual_km')} {km:,} km | {years} {t('prompt_years').lower()}"
    latex = _generate_latex_header(title)
    
    # Summary Table
    latex += r"\section*{Summary}" + "\n"
    summary_rows = [
        [t('label_on_road'), _fmt_vnd(res['on_road'])],
        [t('label_net_tco', y=years), _fmt_vnd(res['tco'])],
    ]
    if show_opp:
        summary_rows.extend([
            [t('label_opp_cost'), _fmt_vnd(res['opp_cost'])],
            [t('label_true_impact'), _fmt_vnd(res['true_financial_impact'])],
        ])
    summary_rows.append([t('label_monthly'), _fmt_vnd(res['monthly'])])
    latex += _section_table(summary_rows)
    
    # Section 1: Initial Outlay
    latex += r"\section*{" + _escape_latex(t('section_initial')) + "}" + "\n"
    initial_rows = [
        [t('label_msrp'), _fmt_vnd(res['price'])],
        [t('label_reg_tax'), _fmt_vnd(res['reg_tax'])],
        [t('label_total_outlay'), _fmt_vnd(res['on_road'])],
    ]
    latex += _section_table(initial_rows)
    
    # Section 2: Operating Costs
    latex += r"\section*{" + _escape_latex(t('section_operating')) + "}" + "\n"
    operating_rows = [
        [t('label_fuel'), _fmt_vnd(res['fuel'])],
        [t('label_maint'), _fmt_vnd(res['maint'])],
        [t('label_legal'), _fmt_vnd(res['legal'])],
        [t('label_operating'), _fmt_vnd(res['operating'])],
    ]
    # Parking & Toll
    pt = res.get('parking_toll')
    if pt:
        operating_rows.extend([
            [t('label_parking_toll'), _fmt_vnd(pt['total_over_period'])],
            ["  " + t('label_parking_monthly'), _fmt_vnd(pt['monthly_parking'])],
            ["  " + t('label_toll_monthly'), _fmt_vnd(pt['monthly_toll'])],
        ])
    latex += _section_table(operating_rows)
    if pt:
        latex += r"\textit{Note: Parking \& Toll estimates are provisions, not included in TCO total.}" + "\n\n"
    
    # Section 3: Resale & Depreciation
    latex += r"\section*{" + _escape_latex(t('section_resale')) + "}" + "\n"
    resale_rows = [
        [t('label_resale'), _fmt_vnd(res['resale'])],
        [t('label_depreciation'), _fmt_vnd(res['depreciation'])],
        [t('label_resale_method') + ": " + t('resale_logic_' + res['resale_logic']), ""],
    ]
    latex += _section_table(resale_rows)
    
    # Liquidity
    raw_liq = res.get('liquidity', '')
    if raw_liq.startswith('Tier 1'):
        liq_disp = t('tier_1')
    elif raw_liq.startswith('Tier 2'):
        liq_disp = t('tier_2')
    else:
        liq_disp = t('tier_3')
    latex += f"{_escape_latex(t('label_liquidity', liq=liq_disp))}\n\n"
    
    # Section 4: Loan / Financing Plan (if provided)
    if loan:
        latex += r"\section*{" + _escape_latex(t('section_loan')) + "}" + "\n"
        loan_rows = [
            [t('label_loan_monthly'), _fmt_vnd(loan['monthly_payment'])],
            [t('label_loan_total_interest'), _fmt_vnd(loan['total_interest'])],
            [t('label_loan_total_repayment'), _fmt_vnd(loan['total_repayment'])],
            [t('label_loan_effective_cost'), _fmt_vnd(loan['effective_cost'])],
        ]
        latex += _section_table(loan_rows)
    
    # Assumptions
    latex += r"\section*{Assumptions}" + "\n"
    latex += _assumptions_box(city, km, years, area, ratio, show_opp)
    
    # Footer
    latex += _generate_latex_footer()
    
    # Write .tex file
    tex_file.write_text(latex, encoding='utf-8')
    
    # Compile to PDF if pdflatex available
    if pdflatex_available:
        try:
            result = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", "-output-directory", str(Path.cwd()), str(tex_file)],
                capture_output=True, text=True, timeout=60
            )
            if result.returncode == 0:
                # Run twice for cross-references
                subprocess.run(
                    ["pdflatex", "-interaction=nonstopmode", "-output-directory", str(Path.cwd()), str(tex_file)],
                    capture_output=True, text=True, timeout=60
                )
                # Clean up auxiliary files
                for ext in ['.aux', '.log', '.out']:
                    aux_file = Path.cwd() / f"{filename_base}{ext}"
                    if aux_file.exists():
                        aux_file.unlink()
                return f"PDF generated: {pdf_file}"
            else:
                return f"LaTeX compilation failed. .tex file saved: {tex_file}\nError: {result.stderr[:500]}"
        except subprocess.TimeoutExpired:
            return f"LaTeX compilation timed out. .tex file saved: {tex_file}"
        except Exception as e:
            return f"PDF generation error: {e}. .tex file saved: {tex_file}"
    else:
        # Generate plain-text fallback
        txt_file = Path.cwd() / f"{filename_base}.txt"
        txt_content = _generate_text_report_single(car_id, year, res, city, km, years, area, ratio, show_opp, loan)
        txt_file.write_text(txt_content, encoding='utf-8')
        return f"pdflatex not found. .tex file saved: {tex_file} and .txt report saved: {txt_file} (install TeX Live or MiKTeX for PDF)"


def generate_pdf_compare(cars_data: list, results: list, year: int, city: str, km: int, years: int, area: int, ratio: float, show_opp: bool, loans: list = None) -> str:
    """Generate PDF for multi-car comparison."""
    pdflatex_available = _check_pdflatex()
    
    filename_base = f"vidrive_compare_{date.today().strftime('%Y%m%d')}"
    tex_file = Path.cwd() / f"{filename_base}.tex"
    pdf_file = Path.cwd() / f"{filename_base}.pdf"
    
    car_ids = [c.upper() for c in cars_data]
    n = len(car_ids)
    
    # Build LaTeX content
    title = " vs ".join(car_ids) + f" | {t('prompt_annual_km')} {km:,} km | {years} {t('prompt_years').lower()}"
    latex = _generate_latex_header(title)
    
    # Summary Comparison Table
    latex += r"\section*{Comparison Summary}" + "\n"
    
    # Build header row
    if n == 2:
        col_spec = "l r r"
        header = ["Metric", car_ids[0], car_ids[1]]
    else:
        col_spec = "l r r r"
        header = ["Metric", car_ids[0], car_ids[1], car_ids[2]]
    
    summary_rows = [header]
    summary_rows.append([
        t('label_on_road'),
        _fmt_vnd(results[0]['on_road']),
        _fmt_vnd(results[1]['on_road']),
    ])
    if n == 3:
        summary_rows[-1].append(_fmt_vnd(results[2]['on_road']))
    
    summary_rows.append([
        t('label_net_tco', y=years),
        _fmt_vnd(results[0]['tco']),
        _fmt_vnd(results[1]['tco']),
    ])
    if n == 3:
        summary_rows[-1].append(_fmt_vnd(results[2]['tco']))
    
    if show_opp:
        summary_rows.append([
            t('label_opp_cost'),
            _fmt_vnd(results[0]['opp_cost']),
            _fmt_vnd(results[1]['opp_cost']),
        ])
        if n == 3:
            summary_rows[-1].append(_fmt_vnd(results[2]['opp_cost']))
        
        summary_rows.append([
            t('label_true_impact'),
            _fmt_vnd(results[0]['true_financial_impact']),
            _fmt_vnd(results[1]['true_financial_impact']),
        ])
        if n == 3:
            summary_rows[-1].append(_fmt_vnd(results[2]['true_financial_impact']))
    
    summary_rows.append([
        t('label_monthly'),
        _fmt_vnd(results[0]['monthly']),
        _fmt_vnd(results[1]['monthly']),
    ])
    if n == 3:
        summary_rows[-1].append(_fmt_vnd(results[2]['monthly']))
    
    # Build the table
    lines = [f"\\begin{{tabular}}{{{col_spec}}}", r"\toprule"]
    for i, row in enumerate(summary_rows):
        if i == 0:
            lines.append(" & ".join(_escape_latex(c) for c in row) + r" \\ \midrule")
        else:
            lines.append(" & ".join(_escape_latex(c) for c in row) + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\vspace{0.5cm}"])
    latex += "\n".join(lines)
    
    # Initial Outlay
    latex += r"\section*{" + _escape_latex(t('section_initial')) + "}" + "\n"
    initial_rows = [["", *car_ids]]
    for k in ['price', 'reg_tax', 'on_road']:
        label = {'price': t('label_msrp'), 'reg_tax': t('label_reg_tax'), 'on_road': t('label_total_outlay')}[k]
        row = [label]
        for r in results:
            row.append(_fmt_vnd(r[k]))
        initial_rows.append(row)
    latex += _section_table(initial_rows, col_count=n)
    
    # Operating Costs
    latex += r"\section*{" + _escape_latex(t('section_operating')) + "}" + "\n"
    operating_rows = [["", *car_ids]]
    for k in ['fuel', 'maint', 'operating']:
        label = {'fuel': t('label_fuel'), 'maint': t('label_maint'), 'operating': t('label_operating')}[k]
        row = [label]
        for r in results:
            row.append(_fmt_vnd(r[k]))
        operating_rows.append(row)
    latex += _section_table(operating_rows, col_count=n)
    
    # Parking & Toll - generate as separate sub-table per car (cleaner layout)
    latex += r"\subsection*{" + _escape_latex(t('label_parking_toll')) + "}" + "\n"
    for i, r in enumerate(results):
        pt = r.get('parking_toll')
        if pt:
            pt_rows = [
                [car_ids[i] + " - " + t('label_parking_monthly'), _fmt_vnd(pt['monthly_parking'])],
                [car_ids[i] + " - " + t('label_toll_monthly'), _fmt_vnd(pt['monthly_toll'])],
                [car_ids[i] + " - Total (" + str(years) + " yr)", _fmt_vnd(pt['total_over_period'])],
            ]
            lines = [r"\begin{tabular}{l r}", r"\toprule"]
            for row in pt_rows:
                lines.append(" & ".join(_escape_latex(c) for c in row) + r" \\")
            lines.extend([r"\bottomrule", r"\end{tabular}", r"\vspace{0.3cm}"])
            latex += "\n".join(lines)
    latex += r"\textit{Note: Parking \& Toll estimates are provisions, not included in TCO total.}" + "\n\n"
    
    # Resale & Depreciation
    latex += r"\section*{" + _escape_latex(t('section_resale')) + "}" + "\n"
    resale_rows = [["", *car_ids]]
    for k in ['resale', 'depreciation']:
        label = {'resale': t('label_resale'), 'depreciation': t('label_depreciation')}[k]
        row = [label]
        for r in results:
            row.append(_fmt_vnd(r[k]))
        resale_rows.append(row)
    latex += _section_table(resale_rows, col_count=n)
    latex += f"{_escape_latex(t('label_resale_method') + ': ' + t('resale_logic_' + results[0]['resale_logic']))}\n\n"
    
    # Brand Liquidity
    liq_rows = [["", *car_ids]]
    row = [t('label_brand_liquidity')]
    for r in results:
        raw_liq = r.get('liquidity', '')
        if raw_liq.startswith('Tier 1'):
            liq_disp = t('tier_1')
        elif raw_liq.startswith('Tier 2'):
            liq_disp = t('tier_2')
        else:
            liq_disp = t('tier_3')
        row.append(liq_disp)
    liq_rows.append(row)
    latex += _section_table(liq_rows, col_count=n)
    
    # Section: Loan / Financing Plan (if provided)
    if loans:
        latex += r"\section*{" + _escape_latex(t('section_loan')) + "}" + "\n"
        loan_rows = [["", *car_ids]]
        for k in ['monthly_payment', 'total_interest', 'total_repayment', 'effective_cost']:
            label = {
                'monthly_payment': t('label_loan_monthly'),
                'total_interest': t('label_loan_total_interest'),
                'total_repayment': t('label_loan_total_repayment'),
                'effective_cost': t('label_loan_effective_cost'),
            }[k]
            row = [label]
            for loan in loans:
                row.append(_fmt_vnd(loan[k]))
            loan_rows.append(row)
        latex += _section_table(loan_rows, col_count=n)
    
    # Verdict
    latex += r"\section*{Verdict}" + "\n"
    min_idx = min(range(n), key=lambda i: results[i]['tco'])
    winner = car_ids[min_idx]
    for i in range(n):
        if i != min_idx:
            diff = results[i]['tco'] - results[min_idx]['tco']
            verdict_text = t('compare_verdict', winner=winner, diff=_fmt_vnd(abs(diff)))
            latex += f"\\textbf{{\\color{{WinnerGreen}} {_escape_latex(verdict_text)}}}\\\\\n"
    
    # Assumptions
    latex += r"\section*{Assumptions}" + "\n"
    latex += _assumptions_box(city, km, years, area, ratio, show_opp)
    
    # Footer
    latex += _generate_latex_footer()
    
    # Write .tex file
    tex_file.write_text(latex, encoding='utf-8')
    
    # Compile to PDF if pdflatex available
    if pdflatex_available:
        try:
            result = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", "-output-directory", str(Path.cwd()), str(tex_file)],
                capture_output=True, text=True, timeout=60
            )
            if result.returncode == 0:
                subprocess.run(
                    ["pdflatex", "-interaction=nonstopmode", "-output-directory", str(Path.cwd()), str(tex_file)],
                    capture_output=True, text=True, timeout=60
                )
                for ext in ['.aux', '.log', '.out']:
                    aux_file = Path.cwd() / f"{filename_base}{ext}"
                    if aux_file.exists():
                        aux_file.unlink()
                return f"PDF generated: {pdf_file}"
            else:
                return f"LaTeX compilation failed. .tex file saved: {tex_file}\nError: {result.stderr[:500]}"
        except subprocess.TimeoutExpired:
            return f"LaTeX compilation timed out. .tex file saved: {tex_file}"
        except Exception as e:
            return f"PDF generation error: {e}. .tex file saved: {tex_file}"
    else:
        # Generate plain-text fallback
        txt_file = Path.cwd() / f"{filename_base}.txt"
        txt_content = _generate_text_report_compare(cars_data, results, year, city, km, years, area, ratio, show_opp, loans)
        txt_file.write_text(txt_content, encoding='utf-8')
        return f"pdflatex not found. .tex file saved: {tex_file} and .txt report saved: {txt_file} (install TeX Live or MiKTeX for PDF)"
